const ENUM_FUNDRAISING_EVENT_STATUS = {
    ACTIVE: 1, //啟動
    INACTIVE: 0, //關閉
};
const ENUM_FUNDRAISING_EVENT_TYPE = {
    DOWN: 1, // 下降
    UP: 2, // 上升
};
const SPECIAL_MESSAGE_CONDITION_MERCHANTS = ['3002599'];

module.exports = {
    ENUM_FUNDRAISING_EVENT_STATUS,
    ENUM_FUNDRAISING_EVENT_TYPE,
    SPECIAL_MESSAGE_CONDITION_MERCHANTS,
};
